// logical operatros

// locigal AND (&&)  T / T = TRUE     F / F = FALSE   T / F = FALSE  F / T = FALSE  
// logiacl OR  (||)  T / F = FALSE     T / F = TRUE   T / T = TRUE   F / T = TRUE
// logical NOT (!)   cagsi    

let var1 = true && true // halkaan mar ayay run noqon kartaa
let var2 = false || false // halkam mar ayay been noqon kartaa
let var3 = !false
console.log(var1)
console.log(var2);

// Ternary Operator

let age=21;
let message= age <= 18 ? "you`re an adult" : "you`re minor";

console.log(message);



